name: Release Minecraft Mod

on:
  push:
    tags:
      - 'v*'  # 只在推送 tag 时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission to gradlew
      run: chmod +x gradlew  # 确保 gradlew 可执行

    - name: Build with Gradle
      run: ./gradlew build  # 使用正确的命令

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/libs/*.jar
        asset_name: MyMod-${{ github.ref_name }}.jar
        asset_content_type: application/java-archive